name: mocap_viz
channels:
  - defaults
dependencies:
  - python=3.11
  - pandas
  - matplotlib
  - scipy
  - numpy
  - pip:
      - mcap
      - mcap-ros2-support
prefix: /home/onur/miniconda3/envs/mocap_viz
